module.exports = {
  MISSING_TOKEN_SETTINGS: 'missing_token_settings',
  ROUTE_NOT_FOUND: 'route_not_found',
  MISSING_AUTHORIZATION: 'missing_authorization',
  INVALID_AUTHORIZATION: 'invalid_authorization',
  INVALID_USER: 'invalid_user',
  PASSWORD_REQUIRED: 'password_required',
  USERNAME_OR_PASSWORD_WRONG: 'username_or_password_wrong',
  MISSING_DB_INFO: 'missing_db_info',
  MISSING_ORIGIN: 'missing_origin',
  PREFERENCE_NOT_FOUND: 'preference_not_found',
  PREFERENCE_ALREADY_EXISTS: 'preference_already_exists',
  MISSING_KEY: 'missing_key',
  PREFERENCE_NOT_DELETEABLE: 'preference_not_deleteable',
};
